### PR TITLE
Editing background & adding title

### PR DESCRIPTION
**Pull request by alexis-rarchaert**

### CODE REVIEW

**Review by justekoro — CHANGES_REQUESTED** [review]
hi, ty for the pull request!
unfortunately, upon checking, design doesn't seem to be responsive engough.

here are screenshots of what i mean:
image
image
image

**Comment by alexis-rarchaert** [comment]
ok i'm going to change this right now

**Comment by justekoro** [comment]
still acting kinda weird to me
image

**Review by justekoro — APPROVED** [review]
Working, nice improvements! It would be cool to add a light mode tho. Approving this one, but that change will be made in the future.

**Comment by justekoro** [comment]
Merging 06/07/22 at arround 7:30PM UTC+2

**Comment by justekoro** [comment]
fermeture de la pull suite à un changement complet du site

**Pull request closed without merging**
